[[nav]]
    name = "Blog"
    url = "/blog/"
    weight = 1

[[nav]]
    name = "Why Pion"
    url = "/why-pion/"
    weight = 2

[[nav]]
    name = "awesome-pion"
    url = "https://github.com/pion/awesome-pion"
    weight = 3

[[nav]]
    name = "WebRTC for the Curious"
    url = "https://webrtcforthecurious.com"
    weight = 4

[[nav]]
    name = "Office Hours"
    url = "https://officehours.siobud.com"
    weight = 5

[[nav]]
    name = "Triage"
    url = "/triage/"
    weight = 6
